
services:
  postgres:
    image: postgres:15
    container_name: postgres_loja_virtual
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loja_virtual
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loja_network

volumes:
  postgres_data:

networks:
  loja_network:
